import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/">홈</Link>
          <Link href="/list">List</Link>
        </div>  
        {children}
        </body>
    </html>
  );
}
// layout.js가 page.js를 담아서 출력한다.
// children 가 page.js라고 생각하면 된다.

// page.js를 보여줄 때
// 1. 옆에 layout.js 있으면 그걸로 page.js 싸맴
// 2. 상위 폴더에 layout.js 있으면 그걸로 1번 싸맴
// 3. 상위상위 폴더에 또 layout.js가 있으면 그걸로 또 1번 싸맴
// 4. 옆에, 상위 폴더에 있는 모든 layout.js로 싸매서 출력함


